### ISSUE TITLE
Individual FAST5 links for rel6 seem to be broken

### ISSUE THREAD

**Issue by pjedge** [nanopore-wgs-consortium/NA12878#72]
For example, I get a 404 when I try
```
wget http://s3.amazonaws.com/nanopore-human-wgs/rel6/Multi_Fast5_Tars/FAB39088-288418386_Multi_Fast5.tar
```

**Comment by mattloose** [comment]
Apologies - we've fixed the links.

wget http://s3.amazonaws.com/nanopore-human-wgs/rel6/Multi_Fast5_Tars/FAB39088-288418386_Multi_Fast5.tar 

should be

wget http://s3.amazonaws.com/nanopore-human-wgs/rel6/MultiFast5Tars/FAB39088-288418386_Multi_Fast5.tar

**Comment by pjedge** [comment]
FYI 2 links are still broken --they need your fix applied and to have the asterisks removed
http://s3.amazonaws.com/nanopore-human-wgs/rel6/Multi_Fast5_Tars/FAB45321*-19064779_Multi_Fast5.tar
http://s3.amazonaws.com/nanopore-human-wgs/rel6/Multi_Fast5_Tars/FAB45321*-285174896_Multi_Fast5.tar

**Comment by mattloose** [comment]
Remixed!  Sorry about that.
